name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: Databricks CI
    runs-on: ubuntu-latest

    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
      BUNDLE_VAR_catalog: ${{ vars.DATABRICKS_CATALOG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check Databricks CLI
        run: databricks version

      - name: Validate Databricks Bundle
        run: databricks bundle validate -t dev
